[Manifest]
Version = 1
MinRux = "0.4.0"

[Package]
Name = "GbCore"
Version = "0.1.0"
Type = "SourceLibrary"
Description = "Game Boy Color emulation core"
License = "MIT"

[Dependencies]
Core = { Path = "../../external/Rux/Packages/Core" }
